--------------------------------------------------------
--  File created - Wednesday-February-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "LAZY"."FOURNISSEUR" 
   (	"ID_FOURNISSEUR" NUMBER(*,0), 
	"NOMFOURNISSEUR" VARCHAR2(255 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_EXPIRATION" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "LAZY"."EMPLOYEE" 
   (	"MATRICULE" NUMBER(*,0), 
	"NOM" VARCHAR2(255 BYTE), 
	"PRENOM" VARCHAR2(255 BYTE), 
	"E_MAIL" VARCHAR2(255 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"SALAIRE" FLOAT(126), 
	"MOT_DE_PASSE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISON
--------------------------------------------------------

  CREATE TABLE "LAZY"."LIVRAISON" 
   (	"ID_LIVRAISON" NUMBER(*,0), 
	"CODE_POSTAL" NUMBER(*,0), 
	"VILLE" VARCHAR2(255 BYTE), 
	"REGION" VARCHAR2(255 BYTE), 
	"DATE_DE_LIVRAISON" DATE, 
	"IDCOMMANDE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACHETER
--------------------------------------------------------

  CREATE TABLE "LAZY"."ACHETER" 
   (	"REF_PRODUIT" NUMBER(*,0), 
	"ID_CLIENT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIE
--------------------------------------------------------

  CREATE TABLE "LAZY"."CATEGORIE" 
   (	"ID_CATEGORIE" NUMBER(*,0), 
	"LIBELLE" VARCHAR2(255 BYTE), 
	"REMISE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("REMISE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "LAZY"."FACTURE" 
   (	"NFACTURE" NUMBER(*,0), 
	"ETAT" VARCHAR2(255 BYTE), 
	"TVA" FLOAT(126), 
	"TOTAL_TVA" FLOAT(126), 
	"TOTAL_HC" FLOAT(126), 
	"TOTAL_TTC" FLOAT(126), 
	"MODEREGLEMENT" VARCHAR2(255 BYTE), 
	"REMISE" FLOAT(126), 
	"MATRICULE" NUMBER(*,0), 
	"ID_COMMANDE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "LAZY"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER(*,0), 
	"DATE_COMMANDE" DATE, 
	"PAIMENT_VALIDE" BLOB, 
	"MODE_LIVRAISON" VARCHAR2(255 BYTE), 
	"NUM_TEL" NUMBER(*,0), 
	"QUANTITE" NUMBER(*,0), 
	"ID_CLIENT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PAIMENT_VALIDE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "LAZY"."PRODUIT" 
   (	"REF_PRODUIT" NUMBER(*,0), 
	"LIBELLE_PRODUIT" VARCHAR2(255 BYTE), 
	"PRIX" FLOAT(126), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"IDCATEGORIE" NUMBER(*,0), 
	"IDFOURNISSEUR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "LAZY"."PROMOTION" 
   (	"IDPROMOTION" NUMBER(*,0), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"POURCENTAGE" FLOAT(126), 
	"IDCATEGORIE" NUMBER(*,0), 
	"REMISE" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("REMISE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "LAZY"."RECLAMATION" 
   (	"IDRECLAMATION" VARCHAR2(20 BYTE), 
	"DATE_RECLAMATION" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"IDFOURNISSEUR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "LAZY"."CLIENT" 
   (	"ID_CLIENT" NUMBER(*,0), 
	"NOM" VARCHAR2(255 BYTE), 
	"PRENOM" VARCHAR2(255 BYTE), 
	"NB_POINTS" VARCHAR2(255 BYTE), 
	"CLASSE" VARCHAR2(255 BYTE), 
	"CADEAU_CLIENT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LAZY.FOURNISSEUR
SET DEFINE OFF;
REM INSERTING into LAZY.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into LAZY.LIVRAISON
SET DEFINE OFF;
REM INSERTING into LAZY.ACHETER
SET DEFINE OFF;
REM INSERTING into LAZY.CATEGORIE
SET DEFINE OFF;
REM INSERTING into LAZY.FACTURE
SET DEFINE OFF;
REM INSERTING into LAZY.COMMANDE
SET DEFINE OFF;
REM INSERTING into LAZY.PRODUIT
SET DEFINE OFF;
REM INSERTING into LAZY.PROMOTION
SET DEFINE OFF;
REM INSERTING into LAZY.RECLAMATION
SET DEFINE OFF;
REM INSERTING into LAZY.CLIENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."FOURNISSEUR_PK" ON "LAZY"."FOURNISSEUR" ("ID_FOURNISSEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."EMPLOYEE_PK" ON "LAZY"."EMPLOYEE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIVRAISON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."LIVRAISON_PK" ON "LAZY"."LIVRAISON" ("ID_LIVRAISON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACHETER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."ACHETER_PK" ON "LAZY"."ACHETER" ("REF_PRODUIT", "ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."CATEGORIE_PK" ON "LAZY"."CATEGORIE" ("ID_CATEGORIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."FACTURE_PK" ON "LAZY"."FACTURE" ("NFACTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."COMMANDE_PK" ON "LAZY"."COMMANDE" ("ID_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."PRODUIT_PK" ON "LAZY"."PRODUIT" ("REF_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."PROMOTION_PK" ON "LAZY"."PROMOTION" ("IDPROMOTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."RECLAMATION_PK" ON "LAZY"."RECLAMATION" ("IDRECLAMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAZY"."CLIENT_PK" ON "LAZY"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "LAZY"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID_FOURNISSEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."FOURNISSEUR" MODIFY ("ID_FOURNISSEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "LAZY"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."EMPLOYEE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIVRAISON
--------------------------------------------------------

  ALTER TABLE "LAZY"."LIVRAISON" MODIFY ("IDCOMMANDE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."LIVRAISON" ADD CONSTRAINT "LIVRAISON_PK" PRIMARY KEY ("ID_LIVRAISON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."LIVRAISON" MODIFY ("ID_LIVRAISON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACHETER
--------------------------------------------------------

  ALTER TABLE "LAZY"."ACHETER" ADD CONSTRAINT "ACHETER_PK" PRIMARY KEY ("REF_PRODUIT", "ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."ACHETER" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."ACHETER" MODIFY ("REF_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIE
--------------------------------------------------------

  ALTER TABLE "LAZY"."CATEGORIE" MODIFY ("REMISE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."CATEGORIE" ADD CONSTRAINT "CATEGORIE_PK" PRIMARY KEY ("ID_CATEGORIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."CATEGORIE" MODIFY ("ID_CATEGORIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "LAZY"."FACTURE" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."FACTURE" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."FACTURE" ADD CONSTRAINT "FACTURE_PK" PRIMARY KEY ("NFACTURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."FACTURE" MODIFY ("NFACTURE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "LAZY"."COMMANDE" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."COMMANDE" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."COMMANDE" MODIFY ("PAIMENT_VALIDE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."COMMANDE" MODIFY ("DATE_COMMANDE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."COMMANDE" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "LAZY"."PRODUIT" MODIFY ("IDFOURNISSEUR" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("REF_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."PRODUIT" MODIFY ("REF_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "LAZY"."PROMOTION" MODIFY ("REMISE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."PROMOTION" ADD CONSTRAINT "PROMOTION_PK" PRIMARY KEY ("IDPROMOTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."PROMOTION" MODIFY ("IDCATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."PROMOTION" MODIFY ("DATE_FIN" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."PROMOTION" MODIFY ("DATE_DEBUT" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."PROMOTION" MODIFY ("IDPROMOTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "LAZY"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK" PRIMARY KEY ("IDRECLAMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."RECLAMATION" MODIFY ("DATE_RECLAMATION" NOT NULL ENABLE);
  ALTER TABLE "LAZY"."RECLAMATION" MODIFY ("IDRECLAMATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "LAZY"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAZY"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LIVRAISON
--------------------------------------------------------

  ALTER TABLE "LAZY"."LIVRAISON" ADD CONSTRAINT "FK9" FOREIGN KEY ("IDCOMMANDE")
	  REFERENCES "LAZY"."COMMANDE" ("ID_COMMANDE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACHETER
--------------------------------------------------------

  ALTER TABLE "LAZY"."ACHETER" ADD CONSTRAINT "FK10" FOREIGN KEY ("REF_PRODUIT")
	  REFERENCES "LAZY"."PRODUIT" ("REF_PRODUIT") ENABLE;
  ALTER TABLE "LAZY"."ACHETER" ADD CONSTRAINT "FK11" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "LAZY"."CLIENT" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "LAZY"."FACTURE" ADD CONSTRAINT "FK6" FOREIGN KEY ("MATRICULE")
	  REFERENCES "LAZY"."EMPLOYEE" ("MATRICULE") ENABLE;
  ALTER TABLE "LAZY"."FACTURE" ADD CONSTRAINT "FK7" FOREIGN KEY ("ID_COMMANDE")
	  REFERENCES "LAZY"."COMMANDE" ("ID_COMMANDE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "LAZY"."COMMANDE" ADD CONSTRAINT "FK5" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "LAZY"."CLIENT" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "LAZY"."PRODUIT" ADD CONSTRAINT "FK2" FOREIGN KEY ("IDCATEGORIE")
	  REFERENCES "LAZY"."CATEGORIE" ("ID_CATEGORIE") ENABLE;
  ALTER TABLE "LAZY"."PRODUIT" ADD CONSTRAINT "FK3" FOREIGN KEY ("IDFOURNISSEUR")
	  REFERENCES "LAZY"."FOURNISSEUR" ("ID_FOURNISSEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTION
--------------------------------------------------------

  ALTER TABLE "LAZY"."PROMOTION" ADD CONSTRAINT "FK1" FOREIGN KEY ("IDCATEGORIE")
	  REFERENCES "LAZY"."CATEGORIE" ("ID_CATEGORIE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "LAZY"."RECLAMATION" ADD CONSTRAINT "FK4" FOREIGN KEY ("IDFOURNISSEUR")
	  REFERENCES "LAZY"."FOURNISSEUR" ("ID_FOURNISSEUR") ENABLE;
